title: Kyle Lyndsey Aguilar # your name (or website title) here
logo: "/images/Headshot.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <input type="text" value="Kyle.Lyndsey.Aguilar@gmail.com" id="myInput">
  <button onclick="myFunction()">Copy text</button>
  <br><br>
  <a href="www.linkedin.com/in/kyle-lyndsey-aguilar/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
